version: '3.3'

volumes:
  database:

services:
  admin:
    image: yatskevichas/sozidateli_admin
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - database:/app/database

  bot:
    image: yatskevichas/sozidateli_bot
    depends_on:
      - admin
    env_file:
      - ./.env
