# Generated by Django 4.2.9 on 2024-01-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название встречи', max_length=150, verbose_name='Название встречи')),
                ('date_created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания встречи', verbose_name='Дата и время создание встречи')),
                ('date_meeting', models.DateTimeField(blank=True, default='2023-11-16 12:28:27.068357', help_text='Дата и время проведения встречи', verbose_name='Дата и время проведения встречи')),
                ('date_modified_at', models.DateTimeField(auto_now=True, help_text='Изменеие в дате/времени встречи', verbose_name='Изменеие в дате/времени встречи')),
                ('location', models.URLField(blank=True, help_text='Ссылка на встречу', verbose_name='Ссылка на встречу')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
            },
        ),
    ]
