# Generated by Django 4.2.9 on 2024-01-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_meeting',
            field=models.DateTimeField(blank=True, help_text='Дата и время проведения встречи', verbose_name='Дата и время проведения встречи'),
        ),
    ]
