# Generated by Django 4.2.9 on 2024-01-20 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_candidate_managers_and_more'),
        ('meetings', '0003_alter_meeting_date_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_for_valanture', to='users.candidate'),
        ),
    ]
