# Generated by Django 4.2.9 on 2024-01-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_meeting_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='candidate',
        ),
    ]
