# Generated by Django 4.2.9 on 2024-02-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_alter_meeting_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, default='Санкт-Петербург, Перекупной переулок, 9', help_text='Место встречи', max_length=200, verbose_name='Место встречи'),
        ),
    ]
