# Generated by Django 4.2.9 on 2024-01-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_candidate_telegram_id_alter_candidate_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='text',
        ),
        migrations.AddField(
            model_name='candidate',
            name='category',
            field=models.CharField(default=True, help_text='Хотите познакомиться с нами на открытой встрече?', max_length=150, verbose_name='Хотите познакомиться с нами на открытой встрече?'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
