# Generated by Django 4.2.9 on 2024-01-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_candidate_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='username',
        ),
    ]
