# Generated by Django 4.2.9 on 2024-01-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_candidate_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='first_name',
        ),
    ]
