# Generated by Django 4.2.9 on 2024-01-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_candidate_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='asd', help_text='Имя', max_length=150, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='category',
            field=models.CharField(help_text='Хотите познакомиться с нами на открытой встрече?', max_length=150, verbose_name='Хотите познакомиться с нами на открытой встрече?'),
        ),
    ]
