# Generated by Django 4.2.9 on 2024-01-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_candidate_name_alter_candidate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='confirm_date',
            field=models.DateTimeField(help_text='Дата и время проведения встречи', null=True, verbose_name='Дата и время проведения встречи'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='category',
            field=models.CharField(help_text='Кому помогаем', max_length=150, verbose_name='Кому помогаем'),
        ),
    ]
