# Generated by Django 4.2.9 on 2024-02-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_candidate_confirm_date_alter_candidate_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='telegram_ID',
            field=models.CharField(blank=True, help_text='Телеграм_ID', max_length=150, unique=True, verbose_name='Телеграм_ID'),
        ),
    ]
