# Generated by Django 4.2.9 on 2024-02-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_candidate_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='id',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='telegram_ID',
            field=models.CharField(blank=True, help_text='Телеграм_ID', max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='Телеграм_ID'),
        ),
    ]
