name: Sozidateli Workflow

on: [push]

jobs:

  build_and_push_to_docker_hub:
    name: Push Admin Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./sozi_adm/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sozidateli_admin:latest


  build_frontend_and_push_to_docker_hub:
    name: Push Bot Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./tg_bot/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sozidateli_bot:latest


  send_message:
    name: Telegram notification
    runs-on: ubuntu-latest
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Sozidateli - push event.