name: Sozidateli Workflow

on: [push]

jobs:

  build_admin_and_push_to_docker_hub:
    name: Push Admin Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./sozi_adm/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sozidateli_admin:latest


  build_bot_and_push_to_docker_hub:
    name: Push Bot Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./tg_bot/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sozidateli_bot:latest

  deploy:
    name: Deploy on Server
    runs-on: ubuntu-latest
    needs:
      - build_admin_and_push_to_docker_hub
      - build_bot_and_push_to_docker_hub

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Copy docker-compose.yml via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22222
        source: "docker-compose.production.yml"
        target: "sozidateli"
    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22222
        script: |
          cd sozidateli/
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S docker compose -f docker-compose.production.yml pull
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S  docker compose -f docker-compose.production.yml down
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S  docker compose -f docker-compose.production.yml up -d
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S  docker compose -f docker-compose.production.yml exec admin poetry run python manage.py makemigrations
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S  docker compose -f docker-compose.production.yml exec admin poetry run python manage.py migrate

  send_message:
    name: Telegram notification
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Sozidateli - success deploy.